language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install fastai_dependencies/torch-1.1.0-cp37-cp37m-linux_x86_64.whl
  - pip install fastai_dependencies/fastai-1.0.58-py3-none-any.whl

script:
  - python -m unittest discover -s biggerquery -t . -p '*.py'
  - python -m unittest discover -s test -p '*.py'